### ISSUE TITLE
What are the advantages comparing to Docker multi-stage build?

### ISSUE THREAD

**Issue by MelwinKfr** [vladaionescu/earthly#57]
Hi, this project is very interesting! 

Still, I probably missed something important but from the README it seems pretty close to Docker multi-stage builds. Could somebody elaborate on the differences/advantages?

Thank you

**Comment by Euphoric** [comment]
The similarity is there. Earthly seems as if author took docker multi-stage build and cranked it up to 11.
My take on advantages is
- Builds only necessary targets instead of whole dockerfile
- Build parallelism, if multiple targets are indpendent, they are built in parallel
- The "success or nothing" setup is nice too. With dockerfile, it is possible that docker images staying behind even when build fails
- Easier to export artifacts out of the build, which is not really possible with dockerfile
- Ability to reference earth other earth files during build

**Comment by MelwinKfr** [comment]
Thank you for having cleared that out with neat bullet points!

**Comment by jschumacher-dexcom** [comment]
Hi there.  For me, the ability to reference other Earthfiles is one of the key features.  Just wanted to note that by setting DOCKER_BUILDKIT=1, docker itself now supports the first two features listed above (building only necessary targets and build parallelism).
